name: Static Site CI
on:
  workflow_run:
    workflows: ["Uptime CI", "Generate graphs"]
    types:
      - completed
  workflow_dispatch:
jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upptime
        uses: upptime/uptime-monitor@master
        with:
          UPPTIME_GH_PAT: ${{ secrets.UPPTIME_GH_PAT }}
          TYPE: static-site
        env:
          GH_PAT: ${{ secrets.UPPTIME_GH_PAT }}
